### ISSUE TITLE
Client Type "docker-v2" doesn't exist

### ISSUE THREAD

**Issue by aulia-adil** [alexanderwolz/keycloak-registry-mapper#11]
I have put the `.jar` file into the `/opt/keycloak/providers/` directory. However, I can't find any "docker-v2" option there. How am I able to find that "docker-v2" option? 

![image](https://github.com/alexanderwolz/keycloak-docker-group-role-mapper/assets/71262004/b3f266a2-50c1-4388-832b-0e5c88287921)

Thank you

**Comment by alexanderwolz** [comment]
Hi @aulia-adil 

You need to [enable the feature](https://www.keycloak.org/server/features ) in your Keycloak build.

Which Keycloak version are you on?
I have an example Dockerfile that enables the docker v2 protocol [here](https://github.com/alexanderwolz/keycloak-docker-group-role-mapper/blob/main/examples/keycloak-with-mapper/Dockerfile) (Keycloak v21.x)

**Comment by aulia-adil** [comment]
Thank you @alexanderwolz for replying.

I have solved the problem. It turns out we need `KC_FEATURES=docker,token-exchange` as an environment variable. Your example really helps me a lot. However, I suggest that you put this environment variable in the setup section to make someone like me avoid this issue.

By the way, I am using Keycloak 21.0.1 in this case. 

Cheers

**Comment by alexanderwolz** [comment]
Hi @aulia-adil 
Thanks for the feedback, I have updated the Readme accordingly.
I'm happy that my work helps you.

BTW: I had issues regarding custom themes with 21.0, so I suggest you update to 21.1+ if you try to introduce your own design.
